### ISSUE TITLE
Refactor publisher module

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#572] opened 2022-09-20 22:48 UTC
In [PR#516](https://github.com/stellar/java-stellar-anchor-sdk/pull/516#discussion_r973499411), The event configuration is tied to specific implementations. We should consider to make the configuration more flexible.

**Comment by marcelosalloum** [comment] 2022-09-22 20:53
Duplicate of https://github.com/stellar/java-stellar-anchor-sdk/issues/569.

**Closed by marcelosalloum** 2022-09-22 20:53 UTC
Labels: technical debt
